### ISSUE TITLE
On initial render, user is "Unknown".

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#107]
The only button that then gets the AppShell to re-render with the correct username is the light-dark mode toggle switch. Having "unknown" as the user causes problems when trying to create a new proposal as the Person is then not known.

**Comment by pahjbo** [comment]
I am not seeing this - can you make it happen reliably?

**Comment by DJWalker42** [comment]
Yep. The first image is immediately after logging in, the second is after clicking the 'light/dark' mode toggle:
<img width="1727" alt="user_unknown" src="https://github.com/orppst/pst-gui/assets/18212149/d0e9799a-ea9c-4252-b736-0ac909899f5a">
<img width="1728" alt="user_PI" src="https://github.com/orppst/pst-gui/assets/18212149/9c3e0601-6edc-469d-b33a-d33dd04f3737">

**Comment by pahjbo** [comment]
Firefox is the same as Chrome, in that it shows "unknown" every time - I think that the App2.tsx code might benefit from being broken up into several components - it might then be clearer what is happening - it is nice style to have the return of the component at the end of the file which is not the case here - there also could be some subtle closure effects going on with the functions defined in other functions...

**Comment by pahjbo** [comment]
it also seems that on firefox and chrome - logging out does not completely log the person out like it does on safari
