### ISSUE TITLE
Syntax highlighting and preview for Justifications

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#112]
For a better user experience we should provide some syntax highlighting for the text format of choice (LATEX, RST, ASCIIDOC, ...) for Justifications. 

Also, it would be nice to have a preview tab to see the text rendered in the format of choice c.f. markdown.

**Comment by AllanEngland** [comment]
[React Syntax Highlighter](https://github.com/react-syntax-highlighter) could be a suitable react component for this.  Using Prism it supports asciidoc, latex & markdown.  Unfortunately reStructuredText is a bit more elusive.

**Comment by AllanEngland** [comment]
[React Ace](https://www.npmjs.com/package/react-ace) would allow us to syntax highlight the edit box, but by default doesn't support the formats we're using.

**Comment by AllanEngland** [comment]
I've put together a little demo on the associated branch that shows a syntax highlighted preview for ascii (react-syntax-highlighter) and a rendered preview for Latex ([react-latex](https://www.npmjs.com/package/react-latex))

Now looking at [React Simple Code Editor](https://github.com/react-simple-code-editor/react-simple-code-editor/blob/main/README.md) for the possibility of highlighting in the editor window.

**Comment by AllanEngland** [comment]
Swapped react-latex to the newer [react-latex-next](https://www.npmjs.com/package/react-latex-next), however both only render previews of latex strings not whole documents.  But it seems to work well for equations.

The data model has just three format types defined, if this is expanded to include something like markdown, it should be quite easy to add a preview for it using something such as [react-markdown](https://www.npmjs.com/package/react-markdown/).

Still looking into react simple code editor.
