### ISSUE TITLE
polaris logo reverts to a missing figure icon 

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#14]
i have no idea what triggers it as of yet. But a refresh of the page will fix it. when it occurs again, ill take a screen shot and update the issue.

**Comment by pahjbo** [comment]
I have seen this happen too

**Comment by AllanEngland** [comment]
This happens for me but only when not on the main application page (pst/gui/tool) and seems to coincide with the authentication refresh.  Log entries are;

trying authentication
Failed to load resource (http 404 error fetching the logo)
setting api url to ....
![Screenshot 2023-10-30 at 15 52 12](https://github.com/orppst/pst-gui/assets/1575651/c0bb336b-84c0-433e-ab99-69f1c5d7b8d7)

**Comment by pahjbo** [comment]
the underlying issue is probably also related to the fact that the backend is only correctly routing the SPA URLs at the top level.

**Comment by alan-stokes** [comment]
so i did a bit of digging on this, as it appeared on my local system again. what i found is that the url when it breaks is this:
http://localhost:8080/pst/gui/tool/proposal/public/polaris4.png
whereas when it works, its this:
http://localhost:8080/pst/gui/public/polaris4.png

so somewhere the /tool/proposal is getting added in which it shoudnt
