### ISSUE TITLE
New Target Dialog should allow coordinate system to be chosen

### ISSUE THREAD

**Issue by pahjbo** [orppst/pst-gui#178]
the new target should should allow for a list of the available org.ivoa.dm.stc.coords.SpaceSys and allow the user to choose - the different choices should potentially lead to different coordinate representations too.

**Comment by pahjbo** [comment]
at the moment the box erroneously shows J2000 and then copies that to the epoch

**Comment by mwapst** [comment]
...ahhh! I will do more reading.
