### ISSUE TITLE
make the autologout time longer

### ISSUE THREAD

**Issue by pahjbo** [orppst/pst-gui#197]
there is quite a short time to the auto logout popup that needs to be pressed to stay logged in - it would be good to increase this somewhat.

The time is set fundamentally by the OIDC authentication token lifetime that is issued by keycloak - it is almost certain that the default lifetime can be changed in keycloak configuration.

It would be nice to add a countdown timer to the pop-up too.

**Comment by Republicof1** [comment]
this has been worked on via #226 (a duplicate issue, created by mistake).
