### ISSUE TITLE
Update proposal summary to a "long" string fails

### ISSUE THREAD

**Issue by AllanEngland** [orppst/pst-gui#21]
API returns a 500 server error containing

{name: "unknown", message: "Network error", stack: {exceptionType: "io.quarkus.arc.ArcUndeclaredThrowableException", statusCode: 500, message: "Error invoking subclass method"}}

If too much text is entered into the summary text area

**Comment by alan-stokes** [comment]
Do you know at what limit that occurs? (i note the error message is very
unhelpful)
if you can find it out, we can limit the input to below that level using
the below code (swiped from NGOT)

<input #titleData
       *[maxlength]="titleMaxCharacterLimit**"*
       class="form-control mx-3"
       formControlName="title"
       id="titleInput"
       type="text"
       [class.is-invalid]="getAbstractControlWithName('title').invalid"
       (focusout)="updateTrimmedTitle(titleData.value)">

**Comment by DJWalker42** [comment]
By printing out ‘summary.length’ in the description portion of the Textarea it would appear that 255 characters is the limit – so some 8-bit integer limit is applied to the string length somewhere.

From: Alan Stokes ***@***.***>
Date: Tuesday, 31 October 2023 at 10:06
To: orppst/pst-gui ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [orppst/pst-gui] Update proposal summary to a "long" string fails (Issue #21)
Do you know at what limit that occurs? (i note the error message is very
unhelpful)
if you can find it out, we can limit the input to below that level using
the below code (swiped from NGOT)

<input #titleData
*[maxlength]="titleMaxCharacterLimit**"*
class="form-control mx-3"
formControlName="title"
id="titleInput"
type="text"
[class.is-invalid]="getAbstractControlWithName('title').invalid"
(focusout)="updateTrimmedTitle(titleData.value)">

**Comment by alan-stokes** [comment]
I'd propose making a NamedConstant with 255 then and hopefully the
maxlength tag will resolve the problem. I'd suspect there will be more of
those in the future. Do we have a constant's file somewhere?

**Comment by DJWalker42** [comment]
I think this stems from the Postgres database imposing a default limit on the column for the proposal summary, its set the type to VARCHAR(255). In fact, that seems to be a default setting for any columns of type VARCHAR.

From: Alan Stokes ***@***.***>
Date: Tuesday, 31 October 2023 at 10:29
To: orppst/pst-gui ***@***.***>
Cc: Darren Walker ***@***.***>, Comment ***@***.***>
Subject: Re: [orppst/pst-gui] Update proposal summary to a "long" string fails (Issue #21)
I'd propose making a NamedConstant with 255 then and hopefully the
maxlength tag will resolve the problem. I'd suspect there will be more of
those in the future. Do we have a constant's file somewhere?

**Comment by pahjbo** [comment]
ultimately this size  is determined at the level of the [ProposalDM](https://github.com/ivoa/ProposalDM) - in auto-generated code at the moment there is no easy mechanism to change an individual field - though we could alter the default value for all fields.

**Comment by DJWalker42** [comment]
The "@jakarta.persistnece.Column" annotation which has a settable parameter called "length", which is defaulted to 255. As Paul says this is in the auto-generated code from the data model.

**Comment by alan-stokes** [comment]
sounds like something we're going to need to limit in many text places in
the UI then.
