### ISSUE TITLE
Save Observation not working

### ISSUE THREAD

**Issue by mwapst** [orppst/pst-gui#231]
Add an observation and click save - nothing happens but web inspector says 

[Error] Failed to load resource: the server responded with a status of 400 (Bad Request) (observations, line 0)
http://localhost:8084//pst/api/proposals/2/observations
[Error] {name: "unknown", message: "Network error", stack: Object}

...the last change to observations/edit.group.tsx was of course me with #200 , but that was just a matter of moving not changing the button, so I can't see what's happened I'm afraid.

**Comment by AllanEngland** [comment]
I've not witnessed this myself, but it's likely related to the unfinished work on multiple targets per observation.  I'll take this issue and try to fix anything that's wrong with 'save new observation'.

**Comment by AllanEngland** [comment]
I believe this is now working.  I can add and edit observations choosing any number of targets for them without errors (at least on my laptop)

It does make me think now that observations would benefit from having their own name; which may have been discussed previously.
