### ISSUE TITLE
authorisation token refresh causes UI refresh

### ISSUE THREAD

**Issue by pahjbo** [orppst/pst-gui#24]
In an attempt to follow [best practices](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-browser-based-apps-14#name-token-mediating-backend) most of the OIDC flow is done on the server side to avoid the possibility of leaking a refresh token, so that only relatively short lived access tokens are exposed in the client side javascript - The code to refresh these tokens is [here](https://github.com/orppst/pst-gui/blob/baa89e7258dc568c5da0c4fd6fb6963ac98c6c8c/src/main/webui/src/auth/Auth.tsx#L53-L99) - this does work for doing the refresh, but has two flaws

1. the code is executing in a way that interacts with the react rendering that causes a page refresh - it needs to be more in the background...
2. it will do a refresh even if the user is truly idle, which will greatly extend the session, potentially leaving an unattended browser "logged in"

**Comment by DJWalker42** [comment]
Not sure if this is related but occasionally I get a '401' page not working error that I cannot get rid of, and which seems to occur on a token refresh but I am unable to confirm that. Quarkus restarts of both the api and gui do not clear the 401 neither does an invalidate cache and restart of IntelliJ. I have to wait for it to clear on its own and for unclear reasons.

**Comment by alan-stokes** [comment]
What i found when that occurred. Was that the 8080 port had been swiped by
something. And the resetting was putting the ui on other random ports. But
then the accessing the database would fail.

**Comment by pahjbo** [comment]
An alternative approach, rather than forcing an asynchronous token refresh in the background - which seems to cause all sorts of problems, is actually to refresh the token in every call to the server - this might seem wasteful, but it has a much clearer logic and means that the token lifetime is then naturally also an inactivity lifetime
