### ISSUE TITLE
Proposal potential multiple Targets in potential multiple Observations

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#246]
The underlying data model has changed to allow an Observation to contain multiple Targets. That is, a Proposal has the potential to have multiple Observations, each with multiple Targets. The code currently assumes that each Observation in a Proposal contains only a single Target. The code needs to be changed to allow for multiple Targets per Observation.

**Comment by AllanEngland** [comment]
The only thing I believe needs changing is how observations are named in the overview panel.  I've raised a pull request that changes them to a short list of targets instead.  Hopefully this is clear and informative.
