### ISSUE TITLE
use npm for package management

### ISSUE THREAD

**Issue by pahjbo** [orppst/pst-gui#248]
need to move away from yarn 1 for js package management, as it is now rather old and there are issues with version resolution - best to  move to npm, as this is the standard and appears to be slightly less inefficient nowadays - it also has npm link command for local development purposes

**Comment by pahjbo** [comment]
the beginnings of some chains are done one the npm-changes branch - however this is still not working as some of the updates are causing breaking changes - e.g going above mantine 7.7 as the introduction of https://mantine.dev/changelog/7-8-0/#uncontrolled-form-mode uncontrolled from mode does create breaking changes with the key prop

**Comment by DJWalker42** [comment]
Just posting this link for future reference [working with lockfiles in workflows](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#working-with-lockfiles)
