### ISSUE TITLE
Petty but the UI scale slider scales with the UI as it slides

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#25]
In other words, should the scale slider be separate and static compared with the the other UI elements which it resizes?

**Comment by alan-stokes** [comment]
this may be a stupid question. but do we need the slider? when the browser itself has such functionality built in by its own zoom?

but on your actual question. I'd be inclined to say that it needs to resize, otherwise itll just look odd being a fixed size tat isnt mathcing the rest of the UI.

**Comment by DJWalker42** [comment]
Closing as we'll remove the UI scale slider from the app.
