### ISSUE TITLE
need to be able to delete a proposal

### ISSUE THREAD

**Issue by pahjbo** [orppst/pst-gui#274]
should be able to delete a proposal if you are the PI

**Comment by DJWalker42** [comment]
Currently, the API can delete a proposal so long as the proposal has yet to define any 'Observations'. If you try to delete a proposal with an 'Observation' it complains with the following error:

`ERROR: null value in column "field_ID" of relation "Observation" violates not-null constraint`

which looks like a database schema issue.

**Comment by DJWalker42** [comment]
A work-around could be implementing a delete handler in the GUI to first remove all Observations from the proposal, then remove the Proposal; the user would still just see a single delete button for a Proposal.
