### ISSUE TITLE
Cannot change "kind" of proposal

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#279]
The only place you can set the "kind" of proposal ("Standard", "T.O.O", "Survey") is on the create new proposal page. I'm not sure if this was intentional. If not we require a change "Kind" input. 

When creating a proposal, it might be better not to use a default value for the "kind" such that is requires the user to use the dropdown menu. 

Coupled with this, I feel like the Title, Summary and Kind can be grouped on to one page.

**Comment by AllanEngland** [comment]
I agree, especially grouping these things onto one page.  That's something I meant to do earlier in the project.  I feel a similar grouping could be done for proposal cycles with title and dates.
