### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#44]
every so often. the entire UI falls down and gives you a 401 error.

it seems that it may that some code is holding onto the 8080 port. As digging into the quarkus speel when booting up, it eventually ends up hosting the UI on some other port. but then fails to be able to talk to the database. Maybe the pst-api-service experiences the same problem and thus kills the UI?

**Comment by alan-stokes** [comment]
plonking this link for usful store. this is where im forwarded to when needing to authenticate. whereas when the 401 starts. This page never appears. so maybe this has something to do with it:

http://localhost:53536/realms/orppst/protocol/openid-connect/auth?response_type=code&client_id=pst-gui&scope=openid&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fpst%2Fgui%2Ftool%2F&state=6db7ac05-4783-4115-b089-902832adeb7b&code_challenge=3VnGrAMR40s0EzqJaRB6JmSZ5LDJs1dV1RVFfX69oDY&code_challenge_method=S256

**Comment by pahjbo** [comment]
it might be that the mechanism that quarkus is using to enable "live" development   https://docs.quarkiverse.io/quarkus-quinoa/dev/main-concepts.html is contributing to this strange behaviour.

**Comment by AllanEngland** [comment]
It happened to me again, this time I opened a new browser and was able to log in and continue testing, while the old browser was still unable to load anything for 401 errors.  Appears to suggest a browser token is old/out of sync (following a quarkus restart) and not replaced until it's expired.  I used a combination of Safari (getting the 401) and Chrome (worked, but only fired up after the error started) to do this, not sure if other browsers behave differently.

**Comment by alan-stokes** [comment]
on the same port? coz if so, ya blown my logic out of the window

**Comment by AllanEngland** [comment]
I think so, but didn't check at the time.  Now having trouble reproducing it but will try again shortly.

**Comment by AllanEngland** [comment]
I managed to replicate this, it was running on the same port and only accessible from the second browser (that had not recently been used on the site).

**Comment by alan-stokes** [comment]
so experienced this whilst trying to see how badly ive screwed up the aladin. and i found clearing the chrome cache was enough to fix the issue.
