### ISSUE TITLE
enum vs string union: code generator

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#47]
can we make the code generator not use this string union and label it a enum, such examples are:

CalibrationTargetIntendedUse, PolStateEnum etc. 

the reason why, is that a string union cannot be utilised by the typescript properly. So far usages of these are manually hard coded to avoid the problem. and as @DJWalker42 has shown, converting between string unions and arrays / enums are a mess of complexities. 

but from a maintenance view point, repeating hardcodings is going to bite us in the butt the moment the union changes at all, and so if we cant easily convert from union to string array. Id propose ensuring the code generator doesn't use these string unions .

**Comment by DJWalker42** [comment]
Closing for the following reasons 

- see [here](https://www.typescriptcourse.com/string-literal-unions-over-enums) 

Consider that for any changes to occur in the unions/enums would require changes to the underlying data model, and we'd have to update front end clients anyway to make use of the data model changes, regardless of using a union or an enum. For compatibility, we'd have to restrict changes to additions only but that is easily managed through the use of string literal unions.
