### ISSUE TITLE
Proposals for "username"

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#5]
clicking on this button in the "navbar" roots the user to the root page which just says "welcome". If this page is meant to list the proposals of the user. Isnt this what the left side of the UI does as well? 

is there a plan to move the filter functionality into this "welcome" page?

**Comment by AllanEngland** [comment]
I imagine a future welcome page to include useful notifications and information such as a list of incomplete proposals, news bulletins or status updates for submitted proposals.  However, these are not all supported by the proposal model (yet) and as 
'nice to haves' may not make it into the pilot phase.
