### ISSUE TITLE
uploading files seem to have broken

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#66]
on master branch. if you try to upload any document, there is a response back along the lines of:

Upload failed
/tmp/documentStore/2/supportingDocuments/5 exists - how'd that happen?!

this seems to occur on any file format. Given i've seen it work previously. This seems to be a regression in functionality.

**Comment by DJWalker42** [comment]
That file store location isn't currently removed when the proposal tool is restarted so you'll have existing, stale locations. At the moment you should just manually remove those directories/files.

**Comment by alan-stokes** [comment]
im obviously too dumb today. what directories / files are we talking about? and I'm confused to why restarting the tool causing stale locations, shouldn't we be detecting a previous directory / files and going "oh ill use that, as it already exists"?

**Comment by AllanEngland** [comment]
The current document store is temporary, the final goal is to have them in permanent storage on a K8s cluster.  Unfortunately, we can't detect and reuse existing files as when the dev environment is restarted the proposals they were linked to no longer exist.  

Manually deleting `/tmp/documentStore/*` on a restart is the best option at the moment.

**Comment by DJWalker42** [comment]
Fixed in the API service by PR #22 in that project. To sum up, on start-up of the api-service we query the database for any supporting documents. If there aren't any then assume that the contents of the document store are stale and recursively remove the document store directory, else do nothing.
