### ISSUE TITLE
review process page

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#8]
needs to be created

**Comment by alan-stokes** [comment]
to add details to this thin issue.

If you look at the NGOT UI, there is a validation page which lists any outstanding issues. 

The Polaris UI likely wishes to have something akin to this. A basic implementation could be made by traversing the proposal and calling the separate pages to make their forms and check for validation errors. those could then be grouped and presented to the user with routing and advice on how to proceed.

**Comment by DJWalker42** [comment]
Closing as this has now been created
