### ISSUE TITLE
Order of Timing Windows changes when you edit them

### ISSUE THREAD

**Issue by DJWalker42** [orppst/pst-gui#84]
When editing Timing windows their order in the list changes, the edited window drops to the bottom of the list.

**Comment by pahjbo** [comment]
I don't think that the model explicitly asks for ordering yet - we need to add that, as the default is unordered

**Comment by pahjbo** [comment]
have published new proposalDM that is requesting these to be ordered - hopefully this will work

**Comment by DJWalker42** [comment]
Timing window order is preserved on edit
