### ISSUE TITLE
home page starts by default with a default value proposal that is odd and is difficult to use due to the observations

### ISSUE THREAD

**Issue by alan-stokes** [orppst/pst-gui#90]
When you boot up the UI and services for the first time. There is a project with name "the proposal title" which is rather difficult to use, as the fictional targets are within a observation, making it impossible to delete/edit them to work with.

Part of me wonders if this means this default needs to disappear, esp if its actually being stored in the database. Or we need to provide more support for that one, such as making targets editable, and / or indications to flag up that these values such as titles etc needs to change.

**Comment by AllanEngland** [comment]
I think this has been sorted by renaming objects in the example proposal so they make more sense.  Also, we now restrict viewing so any new registered users (beyond test/example user `PI`) will not see the example proposal.
